<?php /** @var \Amasty\Shopby\Block\Navigation\State $block */?>
<?php
$filters = $block->getActiveFilters();
$value = [];
?>
<?php if (!empty($filters)): ?>
    <div class="filter-current am-filter-current" id="am-shopby-container" data-am-js="shopby-container"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false }}'>
        <span class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-role="title"
                data-count="<?= /* @noEscape */ count($filters); ?>">
            <?= $block->escapeHtml(__('Now Shopping by')) ?>
        </span>
        <ol class="items">
            <?php foreach ($filters as $filter): ?>
                <?php
                $filterSetting = $block->getFilterSetting($filter->getFilter());
                $value = $value ?: $filter->getValue();
                $resultValue = $block->getFilterValue($value, $filter);
                ?>
                <li class="item am-shopby-item"
                    data-am-js="shopby-item"
                    data-container="<?= /* @noEscape */ $filter->getFilter()->getRequestVar() ?>"
                    data-value="<?= /* @noEscape */ $block->getDataValue($resultValue) ?>"
                >
                    <span class="filter-label"><?= $block->escapeHtml(__($filter->getName())); ?></span>
                    <span class="filter-value am-filter-value"><?= /* @noEscape */ $block->viewLabel($filter);?></span>
                    <?php
                    $clearLinkUrl = $filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtml(__($filter->getName())) . " " .
                        $block->stripTags($filter->getLabel());
                    if ($clearLinkUrl): ?>
                        <a class="action previous" href="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                           title="<?= $block->escapeHtml(__('Previous')) ?>">
                        </a>
                        <a class="amshopby-button -clear -remove"
                           title="<?= $block->escapeHtml($filter->getFilter()->getClearLinkText()) ?>"
                           href="<?= $block->escapeUrl($clearLinkUrl) ?>">
                        </a>
                        <?php
                    else: ?>
                        <a class="amshopby-button -clear -remove"
                           href="<?= $block->escapeUrl($filter->getRemoveUrl($resultValue)) ?>"
                           title="<?= $block->escapeHtml(__('Remove') . " " . $currentFilterName); ?>">
                        </a>
                    <?php endif; ?>
                </li>

                <?php $value = $block->changeValueForMultiselect($filter->getFilter(), $value); ?>
            <?php endforeach; ?>
        </ol>
        <?php if ($block->getUnfoldedCount() && $block->getUnfoldedCount() < count($filters)): ?>
            <?= /* @noEscape */ $block->createShowMoreButtonBlock() ?>
        <?php endif; ?>
        <script type="text/x-magento-init">
        {
            "[data-am-js='shopby-container']": {
                "amShopbyFilterContainer": {}
            }
        }
        </script>
    </div>
<?php endif; ?>
