<?php
use Magento\Framework\App\Action\Action;

/**
 * @var $block Magento\CatalogWidget\Block\Product\ProductsList
 * @var $escaper Magento\Framework\Escaper
 */

// phpcs:disable
$compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);
$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
// phpcs:enable

?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block am-widget <?= /* @noEscape */ $type ?>">
        <?php if ($block->getTitle()): ?>
            <h3 class="block-title amtheme-title"><?= $escaper->escapeHtml(__($block->getTitle())) ?></h3>
        <?php endif ?>
        <div class="block-content content">
            <div class="products wrapper <?= /* @noEscape */ $mode ?> products-<?= /* @noEscape */ $mode ?>">
                <ol class="products list items product-items amtheme-products-secondary -full-width">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info ">
                                <div class="product-photo-wrapper">
                                    <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product photo product-item-photo"
                                       title="<?= $escaper->escapeHtml($_item->getName()) ?>"
                                       aria-label="<?= $escaper->escapeHtml($_item->getName()) ?>">
                                        <?= /* @noEscape */ $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                </div>
                                <div class="product details product-item-details">
                                    <span class="product name product-item-name">
                                        <a title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                           aria-label="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                           href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link">
                                            <?= $escaper->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </span>
                                    <?php if ($templateType): ?>
                                        <?= /* @noEscape */ $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <div class="product-details-action">
                                        <?= /* @noEscape */ $block->getProductPriceHtml($_item, $type) ?>

                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="amtheme-icon-wrapper">
                                                <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                       class="action towishlist amtheme-circle-icon"
                                                       title="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
                                                       aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <svg class="amtheme-icon -hover-bg">
                                                            <use xlink:href="#icon-wishlist" />
                                                        </svg>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                       class="action tocompare amtheme-circle-icon"
                                                       title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                       aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                       data-action="add-to-compare"
                                                       role="button">
                                                        <svg class="amtheme-icon -hover-bg">
                                                            <use xlink:href="#icon-compare"/>
                                                        </svg>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>

                                    <?= /* @noEscape */ $block->getProductDetailsHtml($_item) ?>

                                    <?php if ($showCart): ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                                                      action="<?= isset($postParams['action']) ? $escaper->escapeUrl($postParams['action']) : $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                      method="post">
                                                    <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><?= $escaper->escapeHtml(__('In stock')) ?></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><?= $escaper->escapeHtml(__('Out of stock')) ?></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
