<?php
/**
 * @var $block Amasty\JetTheme\Block\Footer\Layout\ThreeColumns
 */
?>

<div class="amtheme-custom-footer -three-columns">
    <div class="footer-column">
        <?= $block->getFirstColumnsHtml() ?>
    </div>
    <div class="footer-column">
        <?= $block->getSecondColumnsHtml() ?>
    </div>
    <div class="footer-column">
        <?= $block->getThirdColumnsHtml() ?>
    </div>
</div>

