<?php
/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
// 2.3.0 compatibility fix
$isReviewEnabled = method_exists($block, 'isReviewEnabled') ? $block->isReviewEnabled() : true;
?>
<?php if ($isReviewEnabled && $block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary short<?= !$rating ? ' no-rating' : '' ?>">
        <div class="rating-summary">
            <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
            <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating) ?>%">
                <span style="width:<?= $block->escapeHtmlAttr($rating) ?>%"><?= $block->escapeHtml($rating) ?>%</span>
            </div>
        </div>
        <div class="reviews-actions">
            <a class="action view"
               href="<?= $block->escapeUrl($url) ?>"
               title="<?= $block->escapeHtml(__('Reviews')) ?>">
                <?= $block->escapeHtml($block->getReviewsCount()) ?>&nbsp;<span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span>
            </a>
        </div>
    </div>
<?php elseif ($isReviewEnabled && $block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <div class="reviews-actions">
            <a class="action add"
               href="<?= $block->escapeUrl($url) ?>"
               title="<?= $block->escapeHtml(__('Write review')) ?>">
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
