<?php
/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$reviewFormTrigger = 'review-form-open';
$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
// 2.3.0 compatibility fix
$isReviewEnabled = method_exists($block, 'isReviewEnabled') ? $block->isReviewEnabled() : true;
?>

<?php if ($isReviewEnabled && $block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>">
        <?php if ($rating): ?>
            <div class="rating-summary">
                 <span class="label">
                     <?= $block->escapeHtml(__('Rating')) ?>:
                 </span>
                 <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                     <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                         <span>
                             <span itemprop="ratingValue">
                                 <?= $block->escapeHtml($rating); ?>
                             </span>% of <span itemprop="bestRating">100</span>
                         </span>
                     </span>
                 </div>
             </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view"
               title="<?= $block->escapeHtmlAttr(__('Review')) ?>"
               href="<?= $block->escapeUrl($url) ?>">
                <span itemprop="reviewCount">
                    <?= $block->escapeHtml($block->getReviewsCount()) ?>
                </span>&nbsp;
                <span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span>
            </a>
            <a class="action add"
               title="<?= $block->escapeHtmlAttr(__('Add Review')) ?>"
               href="<?= $block->escapeUrl($urlForm) ?>">
                <?= $block->escapeHtml(__('Add Your Review')) ?>
            </a>
        </div>
    </div>
<?php elseif ($isReviewEnabled && $block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
            <a class="action add -no-js-scroll"
               data-amtheme-js="<?= $block->escapeHtml($reviewFormTrigger); ?>"
               title="<?= $block->escapeHtmlAttr(__('Add Review')) ?>"
               href="<?= $block->escapeUrl($urlForm) ?>">
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
