<?php
/**
 * Multishipping checkout billing information
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Billing
 */
?>

<?php
$methods = $block->getMethods();
$methodsCount = count($methods);
$methodsForms = $block->hasFormTemplates() ? $block->getFormTemplates(): [];
?>

<div id="checkout-loader"
     data-role="checkout-loader"
     class="loading-mask"
     data-mage-init='{"billingLoader": {}}'>
    <div class="loader">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
             class="loader-image"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')); ?>" />
    </div>
</div>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $block->getCheckoutData()->getSerializedCheckoutConfigs(); ?>;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
</script>
<div id="checkout" data-bind="scope:'checkoutMessages'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "checkoutMessages": {
                            "component": "Magento_Ui/js/view/messages",
                            "displayArea": "messages"
                        }
                    }
                }
            }
        }
    </script>
</div>
<form action="<?= $block->escapeUrl($block->getPostActionUrl()); ?>"
      method="post"
      id="multishipping-billing-form"
      class="form multicheckout billing">
    <div class="block block-billing">
        <div class="block-content amtheme-address-method">
            <div class="box box-billing-address address">
                <strong class="box-title">
                    <?= $block->escapeHtml(__('Billing Address')); ?>
                </strong>
                <div class="box-content">
                    <address>
                        <?= /* @noEscape */ $block->getCheckoutData()->getAddressHtml($block->getAddress()); ?>
                    </address>
                    <a href="<?= $block->escapeUrl($block->getSelectAddressUrl()); ?>"
                       class="action edit"
                       title="<?= $block->escapeHtml(__('Change Billing Address')); ?>">
                        <?= $block->escapeHtml(__('Change')); ?>
                    </a>
                </div>
            </div>
            <div class="box box-billing-method method">
                <fieldset class="fieldset">
                    <strong class="box-title">
                        <?= $block->escapeHtml(__('Payment Method')); ?>
                    </strong>
                    <div class="box-content">
                        <?= $block->getChildHtml('payment_methods_before') ?>
                        <?php /* Payment methods forms list */ ?>
                        <dl class="checkout-payment-method" id="payment-methods">
                            <?php foreach ($methods as $method):
                                $code = $method->getCode();
                                $checked = $block->getSelectedMethodCode() === $code;

                                if (isset($methodsForms[$code])) {
                                    $block->setMethodFormTemplate($code, $methodsForms[$code]);
                                }
                                ?>
                                <div data-bind="scope: 'payment_method_<?= $block->escapeHtml($code);?>'">
                                    <dt class="item-title">
                                        <?php if ($methodsCount > 1): ?>
                                            <input type="radio"
                                                   id="p_method_<?= $block->escapeHtml($code); ?>"
                                                   value="<?= $block->escapeHtmlAttr($code); ?>"
                                                   name="payment[method]"
                                                   title="<?= $block->escapeHtmlAttr($method->getTitle()) ?>"
                                                   data-bind="
                                                       value: getCode(),
                                                       checked: isChecked,
                                                       click: selectPaymentMethod,
                                                       visible: isRadioButtonVisible()"
                                                <?php if ($checked): ?>
                                                    checked="checked"
                                                <?php endif; ?>
                                                    class="radio"/>
                                        <?php else: ?>
                                            <input type="radio"
                                                   id="p_method_<?= $block->escapeHtml($code); ?>"
                                                   value="<?= $block->escapeHtmlAttr($code); ?>"
                                                   name="payment[method]"
                                                   data-bind="
                                                       value: getCode(),
                                                       afterRender: selectPaymentMethod"
                                                   checked="checked"
                                                   class="radio solo method" />
                                        <?php endif; ?>
                                        <label for="p_method_<?= $block->escapeHtml($code); ?>">
                                            <?= $block->escapeHtml($method->getTitle()) ?>
                                        </label>
                                    </dt>
                                    <?php if ($html = $block->getChildHtml('payment.method.' . $code)): ?>
                                        <dd class="item-content <?= $checked ? '' : 'no-display'; ?>">
                                            <?= /* @noEscape */ $html; ?>
                                        </dd>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        </dl>
                        <?= $block->getChildHtml('payment_methods_after') ?>
                        <?= $block->getChildHtml('checkout_billing_items') ?>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="actions-toolbar -reverse">
        <div class="primary" id="parent-payment-continue">
            <button id="payment-continue"
                    type="button"
                    class="action primary continue"
                    title="<?= $block->escapeHtml(__('Go to Review Your Order')); ?>">
                <?= $block->escapeHtml(__('Go to Review Your Order')); ?>
            </button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()); ?>"
               class="action back"
               title="<?= $block->escapeHtml(__('Back to Shipping Information')); ?>">
                <svg class="amtheme-icon">
                    <use xlink:href="#icon-arrow-left-min"></use>
                </svg>
                <?= $block->escapeHtml(__('Back to Shipping Information')); ?>
            </a>
        </div>
    </div>
</form>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($) {
        var addtocartForm = $('#multishipping-billing-form');

        addtocartForm.mage('payment', {
            checkoutPrice: <?= (float)$block->getQuoteBaseGrandTotal() ?>
        });

        addtocartForm.mage('validation', {
            errorPlacement: function(error, element) {
                if (element.attr('data-validate')
                    && element.attr('data-validate').indexOf('validate-cc-ukss') >= 0) {
                    element.parents('form').find('[data-validation-msg="validate-cc-ukss"]').html(error);
                } else {
                    element.after(error);
                }
            }
        });
    });
</script>

<script>
    //<![CDATA[
    require([
        'Magento_Checkout/js/model/quote',
        'jquery',
        'domReady!'
    ], function(quote, $) {
        quote.billingAddress({
                city: '<?= /* @noEscape */ $block->getAddress()->getCity() ?>',
                company: '<?= /* @noEscape */ $block->getAddress()->getCompany(); ?>',
                countryId: '<?= /* @noEscape */ $block->getAddress()->getCountryId(); ?>',
                customerAddressId: '<?= /* @noEscape */ $block->getAddress()->getCustomerAddressId(); ?>',
                customerId: '<?= /* @noEscape */ $block->getAddress()->getCustomerId(); ?>',
                fax: '<?= /* @noEscape */ $block->getAddress()->getFax(); ?>',
                firstname: '<?= /* @noEscape */ $block->getAddress()->getFirstname(); ?>',
                lastname: '<?= /* @noEscape */ $block->getAddress()->getLastname(); ?>',
                postcode: '<?= /* @noEscape */ $block->getAddress()->getPostcode(); ?>',
                regionId: '<?= /* @noEscape */ $block->getAddress()->getRegionId(); ?>',
                regionCode: '<?= /* @noEscape */ $block->getAddress()->getRegionCode() ?>',
                region: '<?= /* @noEscape */ $block->getAddress()->getRegion(); ?>',
                street: <?= /* @noEscape */ json_encode($block->getAddress()->getStreet()); ?>,
                telephone: '<?= /* @noEscape */ $block->getAddress()->getTelephone(); ?>'
        });
    });
    //]]>
</script>
