<?php
/** @var \Magento\Multishipping\Block\Checkout\Success $block */
?>

<form action="<?= $block->escapeUrl($block->getContinueUrl()); ?>" method="post">
    <div class="multicheckout success">
        <p class="note"><?= $block->escapeHtml(__('For successfully order items, you\'ll receive a confirmation email including '.
                'order numbers, tracking information and more details.')) ?></p>
        <?php if ($orderIds = $block->getOrderIds()): ?>
            <div class="orders-succeed">
                <ul class="orders-list">
                <?php foreach ($orderIds as $orderId => $incrementId): ?>
                    <li class="shipping-list">
                        <div class="order-id">
                            <?= $block->escapeHtml(__('Your Order is:')); ?>
                            <a href="<?= $block->escapeUrl($block->getViewOrderUrl($orderId)); ?>"
                               title="<?= $block->escapeHtml(__('Order Id')); ?>">
                                <?= $block->escapeHtml($incrementId); ?>
                            </a>
                        </div>
                    <?php $shippingAddress = $block->getCheckoutData()->getOrderShippingAddress($orderId); ?>
                        <div class="shipping-item">
                            <?php if ($shippingAddress): ?>
                            <span class="shipping-label"><?= $block->escapeHtml(__('Ship to:')); ?></span>
                            <span class="shipping-address">
                                <?= $block->escapeHtml(
                                    $block->getCheckoutData()->formatOrderShippingAddress($shippingAddress)
                                ); ?>
                            </span>
                            <?php else: ?>
                                <span class="shipping-address">
                                    <?= $block->escapeHtml(__('No shipping required.')); ?>
                                </span>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml() ?>
        <div class="actions-toolbar" id="review-buttons-container">
            <button type="submit"
                    class="action outline submit"
                    title="<?= $block->escapeHtml(__('Continue Shopping')); ?>">
                <?= $block->escapeHtml(__('Continue Shopping')); ?>
                <svg class="amtheme-icon">
                    <use xlink:href="#icon-arrow-right" />
                </svg>
            </button>
        </div>
    </div>
</form>
