<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
/** @var \Magento\Msrp\Helper\Data $helper */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
// phpcs:ignore
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<tbody class="cart item product-item">
    <tr class="item-info">
        <td class="col item" data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>">
            <div class="amtheme-inner">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                       title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                       tabindex="-1"
                       class="product-item-photo">
                <?php else: ?>
                    <span class="product-item-photo">
                <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()): ?>
                    </a>
                <?php else: ?>
                    </span>
                <?php endif; ?>

                <div class="product-item-details">
                    <span class="product-item-name">
                        <?php if ($block->hasProductUrl()): ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                               title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>">
                                <?= $block->escapeHtml($block->getProductName()) ?>
                            </a>
                        <?php else: ?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </span>

                    <?php if ($canApplyMsrp): ?>
                        <div class="msrp pricing">
                            <span class="msrp notice">
                                <?= $block->escapeHtml(__('See price before order confirmation.')) ?>
                            </span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                            <a href="#"
                               class="action help map"
                               title="<?= $block->escapeHtml(__("What's this?")) ?>"
                               id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                               data-mage-init='{"addToCart":{
                                    "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                    "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                    "showAddToCart": false
                                    }
                                }'>
                                <?= $block->escapeHtml(__("What's this?")) ?>
                            </a>
                        </div>
                    <?php else: ?>
                        <div class="price">
                            <?= $block->getUnitPriceHtml($item) ?>
                        </div>
                    <?php endif; ?>

                    <?php if ($options = $block->getOptionList()): ?>
                        <ul class="item-options amtheme-product-options">
                            <?php foreach ($options as $option): ?>
                                <li class="amtheme-item">
                                    <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                    <span class="amtheme-title"><?= $block->escapeHtml($option['label']) ?></span>
                                    <span class="amtheme-value">
                                        <?php if (isset($formatedOptionValue['full_view'])): ?>
                                            <?= $block->escapeHtml($formatedOptionValue['full_view']) ?>
                                        <?php else: ?>
                                            <?= $block->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                        <?php endif; ?>
                                    </span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif;?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                                <span><?= $block->escapeHtml($message['text']) ?></span>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
        </td>
        <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty amtheme-qty-wrap">
                <div class="control amtheme-qty-box" data-mage-init='{"amQty":{}}'>
                    <label class="amtheme-label-small" for="cart-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty">
                        <?= $block->escapeHtml(__('Qty')) ?>
                    </label>
                    <div class="control amtheme-qty-box">
                        <div class="amtheme-minus" data-amtheme-js="qty-minus" tabindex="0" title="Minus">
                            <svg class="amtheme-icon">
                                <use xlink:href="#icon-minus"></use>
                            </svg>
                        </div>
                        <div class="amtheme-plus" data-amtheme-js="qty-plus" tabindex="0" title="Plus">
                            <svg class="amtheme-icon">
                                <use xlink:href="#icon-plus"></use>
                            </svg>
                        </div>
                        <input type="number"
                               class="input-text qty amtheme-qty"
                               data-amtheme-js="qty-input"
                               tabindex="0"
                               id="cart-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"
                        />
                    </div>
                </div>
            </div>
        </td>
        <td class="col subtotal amtheme-column-toolbar">
            <div class="amtheme-cell">
                <div class="subtotal">
                    <span class="amtheme-label-small"><?= $block->escapeHtmlAttr(__('Subtotal')) ?></span>
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart msrp subtotal">--</span>
                    <?php else: ?>
                        <?= $block->getRowTotalHtml($item) ?>
                    <?php endif; ?>
                </div>
            </div>
        </td>
    </tr>
    <tr class="item-actions">
        <td class="col item" colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($item) ?>
            </div>
        </td>
    </tr>
</tbody>
