<?php
/** @var \Amasty\MegaMenuLite\Block\Container $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\MegaMenuLite\ViewModel\Store\Menu $viewModel
 */

$viewModel = $block->getViewModel();
?>

<section class="ammenu-menu-wrapper"
         data-bind="
            scope: 'ammenu_wrapper',
            mageInit: {
                'Magento_Ui/js/core/app': {
                    components: {
                        'ammenu_wrapper': {
                            component: 'Amasty_MegaMenuLite/js/wrapper',
                            data: <?= $escaper->escapeHtml($block->getJsData()) ?>,
                            config: <?= $escaper->escapeHtml($block->getSerializedJsConfig()) ?>,
                            children: <?= $escaper->escapeHtml($block->getJsComponents()) ?>,
                            settings: <?= $escaper->escapeHtml($block->getJsSettings()) ?>,
                            links: <?= $escaper->escapeHtml($block->getStoreLinks()) ?>,
                            isMobile: <?= (int) $viewModel->isMobile() ?>,
                            uniq_name: 'ammenu'
                        }
                    }
                }
            }"
         aria-hidden="true">
        <?php if ($viewModel->isHamburger()): ?>
            <?php if (!$viewModel->isMobile()): ?>
                <?= $block->getChildBlock('ammenu.top.menu')->setItems($block->getHamburgerNodesData())->toHtml() ?>
            <?php endif; ?>
            <!-- ko scope: 'index = hamburger_wrapper' -->
                <!-- ko template: getTemplate() --><!-- /ko -->
            <!-- /ko -->
        <?php endif; ?>
        <?php if (!$viewModel->isHamburger()): ?>
            <?php if ($viewModel->isMobile()): ?>
                <!-- ko scope: 'index = mobile_menu_wrapper' -->
                    <!-- ko template: getTemplate() --><!-- /ko -->
                <!-- /ko -->
            <?php else: ?>
                <?= $block->getChildBlock('ammenu.top.menu')->setItems($block->getAllNodesData())->toHtml() ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($viewModel->isHamburger() || $viewModel->isMobile()): ?>
            <!-- ko scope: 'index = overlay_wrapper' -->
                <!-- ko template: getTemplate() --><!-- /ko -->
            <!-- /ko -->
        <?php endif; ?>
</section>
