<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
    <?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
    <?php $_productsValues = array_values($trackCollection->getItems());?>
    <?php if ($trackCollection): ?>
        <br />
        <div class="amtheme-shipment-track">
            <table class="shipment-track">
                <thead>
                <tr>
                    <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                    <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($trackCollection as $_item): ?>
                    <tr>
                        <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                        <?php if ($block->getTrackingUrl()): ?>
                            <td>
                                <a href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>"
                                   title="<?= $block->escapeHtml(__('Shipment Tracking Number'))?>"
                                   aria-label="<?= $block->escapeHtml(__('Shipment Tracking Number'))?>"
                                   target="_blank">
                                    <?= $block->escapeHtml($_item->getNumber()) ?>
                                </a>
                            </td>
                         <?php else: ?>
                            <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
                         <?php endif; ?>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
<?php endif; ?>
