<?php
/** @var \Magento\Customer\Block\Address\Edit $block */

// phpcs:ignore
$dataHelperClass = $this->helper(\Magento\Directory\Helper\Data::class);
// phpcs:ignore
$addressHelperClass = $this->helper(\Magento\Customer\Helper\Address::class);

$company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class);
$telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class);
$fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class);
$streetValidationClass = $addressHelperClass->getAttributeValidationClass('street');
$streetValidationClassNested = trim(str_replace('required-entry', '', $streetValidationClass));
$streetLines = $addressHelperClass->getStreetLines();
$isVatVisible = $addressHelperClass->isVatAttributeVisible();
$isDefaultOrCanBeDefault = $block->isDefaultBilling()
    || $block->canSetAsDefaultBilling() || $block->isDefaultShipping() || $block->canSetAsDefaultShipping();
?>

<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend">
            <?= $block->escapeHtml(__('Contact Information')) ?>
        </legend>
        <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <div class="fields -double">
            <?= /* @noEscape */ $block->getNameBlockHtml() ?>

            <?php if ($company->isEnabled()): ?>
                <?= /* @noEscape */ $company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php if ($telephone->isEnabled()): ?>
                <?= /* @noEscape */ $telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php if ($fax->isEnabled()): ?>
                <?= /* @noEscape */ $fax->setFax($block->getAddress()->getFax())->toHtml() ?>
            <?php endif ?>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend">
            <?= $block->escapeHtml(__('Address')) ?>
        </legend>
        <div class="field street required">
            <label for="street_1" class="label">
                <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                       id="street_1"
                       class="input-text <?= $block->escapeHtmlAttr($streetValidationClass) ?>"/>
                <div class="nested">
                    <?php for ($i = 1, $n = $streetLines; $i < $n; $i++): ?>
                        <div class="field additional">
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getStreetLine($i + 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $i + 1)) ?>"
                                       id="street_<?= /* @noEscape */ $i + 1 ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($streetValidationClassNested) ?>"
                                />
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="fields -double">
            <?php if ($isVatVisible): ?>
                <div class="field taxvat">
                    <label class="label" for="vat_id">
                        <?= $block->escapeHtml($block->getAttributeData()->getFrontendLabel('vat_id')) ?>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="vat_id"
                               value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                               title="<?= $block->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('vat_id')) ?>"
                               class="input-text <?= $block->escapeHtmlAttr($addressHelperClass->getAttributeValidationClass('vat_id')) ?>"
                               id="vat_id"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="field city required">
                <label class="label" for="city">
                    <?= $block->escapeHtml($block->getAttributeData()->getFrontendLabel('city')) ?>
                </label>
                <div class="control">
                    <input type="text"
                           name="city"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                           class="input-text <?= $block->escapeHtmlAttr($addressHelperClass->getAttributeValidationClass('city')) ?>"
                           id="city"
                    />
                </div>
            </div>
            <div class="field region required">
                <label class="label" for="region_id">
                    <?= $block->escapeHtml($block->getAttributeData()->getFrontendLabel('region')) ?>
                </label>
                <div class="control">
                    <select id="region_id" name="region_id"
                            title="<?= $block->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('region')) ?>"
                            class="validate-select region_id"
                        <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                        <option value="">
                            <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <input type="text"
                           id="region"
                           name="region"
                           value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                           title="<?= $block->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('region')) ?>"
                           class="input-text validate-not-number-first <?= $block->escapeHtmlAttr($addressHelperClass->getAttributeValidationClass('region')) ?>"
                        <?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>
                    />
                </div>
            </div>
            <div class="field zip required">
                <label class="label" for="zip">
                    <?= $block->escapeHtml($block->getAttributeData()->getFrontendLabel('postcode')) ?>
                </label>
                <div class="control">
                    <input type="text"
                           name="postcode"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                           title="<?= $block->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('postcode')) ?>"
                           id="zip"
                           class="input-text validate-zip-international <?= $block->escapeHtmlAttr($addressHelperClass->getAttributeValidationClass('postcode')) ?>">
                    <div role="alert" class="message warning" style="display:none">
                        <span></span>
                    </div>
                </div>
            </div>
            <div class="field country required">
                <label class="label" for="country">
                    <?= $block->escapeHtml($block->getAttributeData()->getFrontendLabel('country_id')) ?>
                </label>
                <div class="control">
                    <?= /* @noEscape */  $block->getCountryHtmlSelect() ?>
                </div>
            </div>
        </div>
        <div class="fields -am-block<?= $isDefaultOrCanBeDefault ? '' : ' -hidden' ?>">
            <?php if ($block->isDefaultBilling()): ?>
                <div class="message info">
                    <span><?= $block->escapeHtml(__("It's a default billing address.")) ?></span>
                </div>
            <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <div class="field choice set billing">
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox" />
                    <label class="label" for="primary_billing">
                        <?= $block->escapeHtml(__('Use as default billing address')) ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_billing" value="1" />
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()): ?>
                <div class="message info">
                    <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
                </div>
            <?php elseif ($block->canSetAsDefaultShipping()): ?>
                <div class="field choice set shipping">
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox" />
                    <label class="label" for="primary_shipping">
                        <?= $block->escapeHtml(__('Use as default shipping address')) ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_shipping" value="1" />
            <?php endif; ?>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    aria-label="<?= $block->escapeHtmlAttr(__('Save Address')) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <?= $block->escapeHtml(__('Save')) ?>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
               title="<?= $block->escapeHtmlAttr(__('Go back')) ?>"
               href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <?= $block->escapeHtml(__('Go back')) ?>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
            <?php if ($block->getPostCodeConfig()): ?>
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            <?php endif ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $dataHelperClass->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $dataHelperClass->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
