<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>

<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit"
       href="<?= $block->escapeUrl($block->getConfigureUrl()) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Edit')) ?>"
       title="<?= $block->escapeHtmlAttr(__('Edit item parameters')) ?>">
        <?= $block->escapeHtml(__('Edit')) ?>
    </a>
<?php endif ?>
