<?php
/**
 * @var \Amasty\MegaMenuLite\Block\Container $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\MegaMenuLite\ViewModel\Store\Menu $viewModel
 */

$viewModel = $block->getViewModel();
$key = $block->getData('key');
$item = $block->getData('item');
$isIconsAvailable = $block->getData('isIconsAvailable');
?>

<li class="ammenu-item category-item nav-<?= (int) $key ?>"
    data-bind="
        scope: 'ammenu_topmenu_item_<?= (int) $key ?>',
        mageInit: {
            'Magento_Ui/js/core/app': {
                components: {
                    'ammenu_topmenu_item_<?= (int) $key ?>': {
                        component: 'Amasty_MegaMenuLite/js/top_menu/item',
                        elemIndex: <?= (int) $key ?>,
                        item: <?= $escaper->escapeHtml($viewModel->serialize($item)) ?>
                    }
                }
            }
        }">

    <?= $block->getChildBlock('ammenu.top.menu.link')->setData('item', $item)->setData('isIconsAvailable', $isIconsAvailable)->toHtml() ?>

    <!-- ko scope: 'index = submenu_wrapper' -->
        <!-- ko template: { name: getTemplate(), data: $parent.item } --><!-- /ko -->
    <!-- /ko -->
</li>
