<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 * @var $escaper Magento\Framework\Escaper
 * @var $_helper Magento\Catalog\Helper\Output
 */

// phpcs:disable
$compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);
$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
$postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
// phpcs:enable

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-list';
    $mode = 'list';
    $image = 'new_products_content_widget_list';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
}
?>

<?php if ($exist): ?>
    <div class="block am-widget block-new-products <?= /* @noEscape */ $mode ?>">
        <h3 class="block-title amtheme-title"><?= $escaper->escapeHtml($title) ?></h3>
        <div class="block-content">
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php foreach ($items as $_item): ?>
                        <li class="item product product-item">
                            <div class="product-item-info">
                                <div class="product-photo-wrapper">
                                    <a title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                       aria-label="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                       href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= /* @noEscape */ $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                </div>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                           aria-label="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                           href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link">
                                            <?= $escaper->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                    <?php if ($templateType): ?>
                                        <?= /* @noEscape */ $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showDescription): ?>
                                        <div class="product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute(
                                                $_item,
                                                $_item->getShortDescription(),
                                                'short_description'
                                            ) ?>
                                            <a title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                               aria-label="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="product-item-inner">
                                    <?= $block->getProductPriceHtml($_item, $type) ?>
                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <?php $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]) ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                    type="button"
                                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                            </button>
                                                        <?php else: ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @noEscape */ $postData ?>'
                                                                    type="button"
                                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><?= $escaper->escapeHtml(__('In stock')) ?></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><?= $escaper->escapeHtml(__('Out of stock')) ?></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="amtheme-icon-wrapper">
                                                    <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                           class="action towishlist"
                                                           title="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
                                                           aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
                                                           data-action="add-to-wishlist"
                                                           role="button">
                                                            <?= $escaper->escapeHtml(__('Add to Wishlist')) ?>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                           class="action tocompare"
                                                           title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                           aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                           data-action="add-to-compare"
                                                           role="button">
                                                            <?= $escaper->escapeHtml(__('Add to Compare')) ?>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= /* @noEscape */ $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
