<?php
/* @var $block \Magento\Sales\Block\Order\PrintOrder\Shipment */

$order = $block->getOrder();

if (!$block->getObjectData($order, 'is_virtual')): ?>
    <?php foreach ($block->getShipmentsCollection() as $shipment): ?>
        <div class="order-details-items shipments">
            <div class="order-title">
                <?= $block->escapeHtml(__('Shipment #%1', $block->getObjectData($shipment, 'increment_id'))) ?>
            </div>
            <div class="table-wrapper order-items-shipment">
                <table class="data table table-order-items shipment"
                       id="my-shipment-table-<?= (int) $block->getObjectData($shipment, 'id') ?>">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Items Invoiced')) ?></caption>
                    <thead>
                        <tr>
                            <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                            <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                            <th class="col price"><?= $block->escapeHtml(__('Qty Shipped')) ?></th>
                        </tr>
                    </thead>
                    <?php foreach ($block->getShipmentItems($shipment) as $item): ?>
                        <tbody>
                            <?= $block->getItemHtml($item) ?>
                        </tbody>
                    <?php endforeach; ?>
                </table>
            </div>
            <div class="block block-order-details-view">
                <div class="block-title">
                    <?= $block->escapeHtml(__('Order Information')) ?>
                </div>
                <div class="block-content">
                    <?php if (!$order->getIsVirtual()): ?>
                        <div class="box column -address box-order-shipping-address">
                            <div class="box-title">
                                <strong><?= $block->escapeHtml(__('Shipping Address')) ?></strong>
                            </div>
                            <address class="box-content">
                                <?= $block->getShipmentAddressFormattedHtml($shipment) ?>
                            </address>
                        </div>
                    <?php endif; ?>

                    <div class="box column -address box-order-billing-address">
                        <div class="box-title">
                            <strong><?= $block->escapeHtml(__('Billing Address')) ?></strong>
                        </div>
                        <address class="box-content">
                            <?= $block->getBillingAddressFormattedHtml($order) ?>
                        </address>
                    </div>

                    <div class="column -methods">
                        <?php if (!$order->getIsVirtual()): ?>
                            <div class="box box-order-shipping-method">
                                <div class="box-title">
                                    <strong><?= $block->escapeHtml(__('Shipping Method')) ?></strong>
                                </div>
                                <div class="box-content">
                                    <?= $block->escapeHtml($block->getObjectData($order, 'shipping_description')) ?>
                                    <?php $tracks = $block->getShipmentTracks($shipment);
                                    if ($tracks): ?>
                                        <div class="order-tracking">
                                            <?php foreach ($tracks as $track): ?>
                                            <span class="wrapper">
                                                <span class="tracking-title"><?= $block->escapeHtml($block
                                                        ->getObjectData($track, 'title')) ?></span>
                                                <span class="tracking-content"><?= $block->escapeHtml($block
                                                        ->getObjectData($track, 'number')) ?></span>
                                            </span>
                                            <?php endforeach; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <div class="box box-order-billing-method<?= $order->getIsVirtual() ? ' -fullwidth' : ''?>">
                            <div class="box-title">
                                <strong><?= $block->escapeHtml(__('Payment Method')) ?></strong>
                            </div>
                            <div class="box-content">
                                <?= $block->getPaymentInfoHtml() ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
