<?php
/** @var $block Magento\Framework\View\Element\Template */
?>

<div class="amtheme-compare-link" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="amtheme-link compare"
       title="<?= $block->escapeHtml(__('Compare Products')) ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'-show': !!compareProducts().count}">
        <svg class="amtheme-icon">
            <use xlink:href="#icon-compare"/>
        </svg>
        <span><?= $block->escapeHtml(__('Compare')) ?></span>
        <span class="amtheme-counter" data-bind="text: compareProducts().count"></span>
    </a>
</div>
<script type="text/x-magento-init">
{
    "[data-role='compare-products-link']": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
