<?php
/* @var \Magento\Wishlist\Block\Share\Email\Items $block */
?>
<?php $l = $block->getWishlistItemsCount() ?>
<div>
    <table class="amtheme-email-wishlist">
        <tr>
            <?php $i = 0;
            foreach ($block->getWishlistItems() as $item): $i++?>
            <?php /* @var $item \Magento\Wishlist\Model\Item */ ?>
            <?php /* @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $_product = $item->getProduct(); ?>
            <td class="col product amtheme-product">
                <p>
                    <a class="amtheme-image"
                       href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                       title="<?= $block->escapeHtml(__("Product Image")) ?>">
                        <?= /* @noEscape */ $block->getImage($_product, 'product_small_image')->toHtml() ?>
                    </a>
                </p>

                <p>
                    <a class="amtheme-name"
                       href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                       title="<?= $block->escapeHtml($_product->getName()) ?>">
                        <?= $block->escapeHtml($_product->getName()) ?>
                    </a>
                </p>
                <?php if ($block->hasDescription($item)): ?>
                    <p class="amtheme-description">
                        <strong><?= $block->escapeHtml(__('Comment')) ?>:</strong>
                        <br/><?= /* @noEscape */  $block->getEscapedDescription($item) ?>
                    </p>
                <?php endif; ?>
                <p>
                    <a class="amtheme-view"
                       href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                       title="<?= $block->escapeHtml(__("View Product")) ?>">
                        <?= $block->escapeHtml(__('View Product')) ?>
                    </a>
                </p>
            </td>
            <?php if ($i % 3 != 0): ?>
                <td></td>
            <?php else: ?>
        </tr>
        <tr>
            <td colspan="5">&nbsp;</td>
        </tr>
        <?php if ($i < $l): ?>
        <tr>
            <?php endif ?>
            <?php endif ?>
            <?php endforeach ?>
    </table>
</div>
