<?php
/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi
 * @var $escaper Magento\Framework\Escaper
 */

$_option = $block->getOption();
$_selections = $_option->getSelections();
?>

<div class="field option <?= ($_option->getRequired()) ? 'required': '' ?>">
    <label class="label" for="bundle-option-<?= $escaper->escapeHtml($_option->getId()) ?>">
        <?= $escaper->escapeHtml($_option->getTitle()) ?>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <div class="amtheme-item-text">
                <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       name="bundle_option[<?= $escaper->escapeHtml($_option->getId()) ?>]"
                       value="<?= $escaper->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
                       class="bundle-option-<?= $escaper->escapeHtml($_option->getId()) ?> bundle option"/>
            </div>
        <?php else: ?>
            <select multiple="multiple"
                    size="5"
                    tabindex="-1"
                    id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $escaper->escapeHtml($_option->getId()) ?>][]"
                    data-selector="bundle_option[<?= $escaper->escapeHtml($_option->getId()) ?>][]"
                    class="amtheme-select
                           bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>
                           multiselect product bundle option change-container-classname"
                    <?php if ($_option->getRequired()) { echo 'data-validate={required:true}'; } ?>>
                <?php if (!$_option->getRequired()): ?>
                    <option value=""><?= $escaper->escapeHtml(__('None')) ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            <?php if ($block->isSelected($_selection)) { echo ' selected="selected"'; } ?>
                            <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>>
                        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <div class="amtheme-select-block"
                 name="[<?= $escaper->escapeHtml($_option->getId()) ?>][]"
                 data-mage-init='{"amSelect": {
                     "selectId": "bundle-option-<?= $escaper->escapeHtml($_option->getId()) ?>",
                     "selectType": "multiple"
                  }}'
                 data-amselect-js="select">
                    <span role="button" tabindex="0" class="amtheme-placeholder" data-amselect-js="placeholder">
                        <span class="amtheme-content" data-amselect-js="placeholder-content">
                            <?= $escaper->escapeHtml(__('Choose a selection...')) ?>
                        </span>
                    </span>
                <ul role="list" class="amtheme-select-options" data-amselect-js="options">
                    <?php if (!$_option->getRequired()): ?>
                        <li class="amtheme-option"
                            tabindex="0"
                            data-amselect-js="item"
                            data-amselect-value="">
                            <?= $escaper->escapeHtml(__('None')) ?>
                        </li>
                    <?php endif; ?>
                    <?php foreach ($_selections as $_selection): ?>
                        <li class="amtheme-option"
                            tabindex="0"
                            data-amselect-js="item"
                            data-amselect-value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            <?php if ($block->isSelected($_selection)) { echo ' selected="selected"'; } ?>
                            <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>>
                            <?php $block->setFormatProduct($_selection); ?>
                            <span class="product-name"><?= (int)$_selection->getSelectionQty() * 1
                                . ' x '
                                . $escaper->escapeHtml($_selection->getName()); ?></span>
                            <span class="price-box">
                                <?= /* @noEscape */ $block->renderPriceString($_selection, false) ?>
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
</div>
