<?php
/**
 * @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio
 * @var $viewModel Amasty\JetTheme\ViewModel\ProductCaret\ProductCaretConfigurationViewModel
 */

$_option = $block->getOption();
$_selections = $_option->getSelections();
$_default = $_option->getDefaultSelection();
list($_defaultQty, $_canChangeQty) = $block->getDefaultValues();
$hasTierPriceRender = (bool) $block->getTierPriceRenderer();
$viewModel = $block->getViewModel();
$isProductCaretEnabled = $viewModel ?  $viewModel->isProductCaretEnabled() : false;
?>

<div class="field option <?= ($_option->getRequired()) ? 'required': '' ?> <?= $isProductCaretEnabled ? 'amtheme-collapsible-block' : '' ?>"
    <?php if ($isProductCaretEnabled): ?>
        data-amcollapsible="block"
        data-mage-init='{
            "amCollapsible":{
                "isMobileOnly": false,
                "isActive": true,
                "isDisabled": true
            }}'
    <?php endif; ?>
>
    <label class="label <?= $isProductCaretEnabled ? 'block-title' : '' ?>"
        <?php if ($isProductCaretEnabled): ?>
            data-amcollapsible="title"
        <?php endif; ?>
    >
        <?= $block->escapeHtml($_option->getTitle()) ?>
        <?php if ($isProductCaretEnabled): ?>
            <svg class="amtheme-icon">
                <use xlink:href="#icon-arrow-bottom"></use>
            </svg>
        <?php endif; ?>
    </label>
    <div class="control"
        <?php if ($isProductCaretEnabled): ?>
            data-amcollapsible="content"
        <?php endif; ?>
    >
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <div class="amtheme-item-text">
                    <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
                    <?php if ($hasTierPriceRender): ?>
                        <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
                    <?php endif; ?>
                    <input type="hidden"
                        class="bundle-option-<?= (int)$_option->getId() ?>  product bundle option"
                        name="bundle_option[<?= (int)$_option->getId() ?>]"
                        value="<?= (int)$_selections[0]->getSelectionId() ?>"
                        id="bundle-option-<?= (int)$_option->getId() ?>-<?= (int)$_selections[0]->getSelectionId() ?>"
                        checked="checked"
                    />
                </div>
            <?php else:?>
                <?php if (!$_option->getRequired()): ?>
                    <div class="field choice amtheme-bundle-choice">
                        <input type="radio"
                               class="radio product bundle option"
                               id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>"
                               name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                               data-selector="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                               <?= ($_default && $_default->isSalable())?'':' checked="checked" ' ?>
                               value=""/>
                        <label class="label amtheme-label amtheme-item-text"
                               for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>">
                            <?= $block->escapeHtml(__('None')) ?>
                        </label>
                    </div>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <div class="field choice amtheme-bundle-choice">
                        <input type="radio"
                               class="radio product bundle option change-container-classname"
                               id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-<?= $block->escapeHtml($_selection->getSelectionId()) ?>"
                               <?php if ($_option->getRequired()) { echo 'data-validate="{\'validate-one-required-by-name\':true}"'; }?>
                               name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                               data-selector="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                               <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                               <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>
                               value="<?= $block->escapeHtml($_selection->getSelectionId()) ?>"/>
                        <label class="label amtheme-label amtheme-item-text"
                               for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-<?= $block->escapeHtml($_selection->getSelectionId()) ?>">
                            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection) ?>
                            <?php if ($hasTierPriceRender): ?>
                                <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                            <?php endif; ?>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-container"></div>
            <?php endif; ?>
            <div class="field qty qty-holder amtheme-qty-wrap">
                <label class="label amtheme-label" for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </label>
                <div class="control amtheme-qty-box" data-mage-init='{"amQty":{}}'>
                    <div class="amtheme-minus"
                         data-amtheme-js="qty-minus"
                         tabindex="0"
                         title="<?= $block->escapeHtml(__('Minus')) ?>">
                        <svg class="amtheme-icon">
                            <use xlink:href="#icon-minus"/>
                        </svg>
                    </div>
                    <div class="amtheme-plus"
                         data-amtheme-js="qty-plus"
                         tabindex="0"
                         title="<?= $block->escapeHtml(__('Plus')) ?>">
                        <svg class="amtheme-icon">
                            <use xlink:href="#icon-plus"/>
                        </svg>
                    </div>
                    <input type="number"
                           name="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                           id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input"
                           min="0"
                           class="input-text qty amtheme-qty <?php if (!$_canChangeQty) { echo 'qty-disabled'; } ?>"
                           value="<?= $block->escapeHtml($_defaultQty) ?>"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           tabindex="0"
                           data-amtheme-js="qty-input"
                           data-selector="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                           <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                    />
                </div>
            </div>
        </div>
    </div>
</div>
