<?php
/**
 * @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select
 * @var $escaper Magento\Framework\Escaper
 */

$_option = $block->getOption();
$_selections = $_option->getSelections();
$_default = $_option->getDefaultSelection();
list($_defaultQty, $_canChangeQty) = $block->getDefaultValues();
$hasTierPriceRender = (bool) $block->getTierPriceRenderer();
?>

<div class="field option <?= ($_option->getRequired()) ? 'required' : '' ?>">
    <label class="label" for="bundle-option-<?= $escaper->escapeHtml($_option->getId()) ?>">
        <?= $escaper->escapeHtml($_option->getTitle()) ?>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <div class="amtheme-item-text">
                <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
                <?php if ($hasTierPriceRender): ?>
                    <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
                <?php endif; ?>
                <input type="hidden"
                       class="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                       name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                       value="<?= $escaper->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
            </div>
        <?php else:?>
            <select id="bundle-option-<?= $escaper->escapeHtml($_option->getId()) ?>"
                    name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                    tabindex="-1"
                    data-selector="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                    class="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>
                           product bundle option bundle-option-select change-container-classname amtheme-select"
                <?php if ($_option->getRequired()): ?>
                    <?= /* @noEscape */ ' data-validate = {required:true}'?>
                <?php endif; ?>
               >
                <option value="">
                    <?= $escaper->escapeHtml(__('Choose a selection...')) ?>
                </option>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                        <?php if ($block->isSelected($_selection)): ?>
                            <?= /* @noEscape */ ' selected="selected"'?>
                        <?php endif; ?>

                        <?php if (!$_selection->isSaleable()): ?>
                            <?= /* @noEscape */ ' disabled="disabled"'?>
                        <?php endif; ?>
                    >
                        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <div class="amtheme-select-block"
                 name="[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                 data-mage-init='{"amSelect": {
                     "selectId": "bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                     }
                 }'
                 data-amselect-js="select">
                <span role="button" tabindex="0" class="amtheme-placeholder" data-amselect-js="placeholder">
                    <span class="amtheme-content" data-amselect-js="placeholder-content">
                        <?= $escaper->escapeHtml(__('Choose a selection...')) ?>
                    </span>
                </span>
                <ul role="list" class="amtheme-select-options" data-amselect-js="options" >
                    <li class="amtheme-option" tabindex="0" data-amselect-js="item">
                        <?= $escaper->escapeHtml(__('Choose a selection...')) ?>
                    </li>
                    <?php foreach ($_selections as $_selection): ?>
                        <li class="amtheme-option"
                            tabindex="0"
                            data-amselect-js="item"
                            <?php if ($block->isSelected($_selection)): ?>
                                <?= /* @noEscape */ ' selected="selected"'?>
                            <?php endif; ?>

                            <?php if (!$_selection->isSaleable()): ?>
                                <?= /* @noEscape */ ' disabled="disabled"'?>
                            <?php endif; ?>
                            data-amselect-value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span class="product-name">
                                <?= $escaper->escapeHtml($_selection->getName()); ?>
                            </span>
                            <span class="price-box">
                                <?= /* @noEscape */ $block->renderPriceString($_selection, false) ?>
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul>
           </div>
            <?php if ($hasTierPriceRender): ?>
                <div id="option-tier-prices-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                     class="option-tier-prices">
                    <?php foreach ($_selections as $_selection): ?>
                        <div data-role="selection-tier-prices"
                             data-selection-id="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                             class="selection-tier-prices">
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <div class="nested">
            <div class="field qty amtheme-qty-wrap qty-holder">
                <label class="label amtheme-label"
                       for="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </label>
                <div class="control amtheme-qty-box" data-mage-init='{"amQty":{}}'>
                    <div class="amtheme-minus"
                         data-amtheme-js="qty-minus"
                         tabindex="0"
                         title="<?= $escaper->escapeHtmlAttr(__('Minus')) ?>">
                        <svg class="amtheme-icon">
                            <use xlink:href="#icon-minus"/>
                        </svg>
                    </div>
                    <div class="amtheme-plus"
                         data-amtheme-js="qty-plus"
                         tabindex="0"
                         title="<?= $escaper->escapeHtmlAttr(__('Plus')) ?>">
                        <svg class="amtheme-icon">
                            <use xlink:href="#icon-plus"/>
                        </svg>
                    </div>
                    <input type="number"
                           name="bundle_option_qty[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                           id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                           min="0"
                           class="input-text qty amtheme-qty <?= !$_canChangeQty ? 'qty-disabled' : '' ?>"
                           value="<?= $escaper->escapeHtmlAttr($_defaultQty) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                           tabindex="0"
                           data-amtheme-js="qty-input"
                           data-selector="bundle_option_qty[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                           data-validate="<?= $escaper->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                        <?php if (!$_canChangeQty): ?>
                            <?= /* @noEscape */ ' disabled="disabled"'?>
                        <?php endif; ?>
                    />
                </div>
            </div>
        </div>
    </div>
</div>
