<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */

$nameIconView = 'icon-close';

?>

<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<div class="filter-current">
    <strong class="block-subtitle filter-current-subtitle"
            role="heading"
            aria-level="2"
            data-count="<?= /* @noEscape */ count($_filters) ?>"><?= $block->escapeHtml(__('Now Shopping by')) ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): ?>
            <li class="item">
                <span class="filter-label"><?= $block->escapeHtml(__($_filter->getName())) ?></span>
                <span class="filter-value"><?= $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName()) . " " . $block->stripTags($_filter->getLabel()));
                if ($clearLinkUrl):
                    ?>
                    <a class="action previous" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?= $block->escapeHtml(__('Previous')) ?>">
                        <span><?= $block->escapeHtml(__('Previous')) ?></span>
                    </a>
                    <a class="action remove"
                       title="<?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       aria-label="<?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?= $block->escapeUrl($clearLinkUrl) ?>">
                        <svg class="amtheme-icon" focusable="false">
                            <use xlink:href="#<?= $block->escapeHtml($nameIconView) ?>"/>'
                        </svg>
                    </a>
                <?php else: ?>
                    <a class="action remove" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?= /* @noEscape */ $block->escapeHtml(__('Remove')) . " " . $currentFilterName ?>"
                       aria-label="<?= /* @noEscape */ $block->escapeHtml(__('Remove')) . " " . $currentFilterName ?>">
                        <svg class="amtheme-icon" focusable="false">
                            <use xlink:href="#<?= $block->escapeHtml($nameIconView) ?>"/>'
                        </svg>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
