<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
    <div class="bundle-summary">
        <?= $block->getChildHtml('', true) ?>
    </div>

    <script type="text/x-magento-init">
        {
            ".product-add-form": {
                "amBundleVisibility": {
                    <?php if ($block->isStartCustomization()): ?>
                    "autostart": true
                    <?php endif;?>
                }
            }
        }
    </script>
<?php endif; ?>
