<?php
/** @var \Amasty\ShopbyLite\Block\Navigation\Component\FilterCollapsing $block */
?>
<script type="text/x-magento-init">
            {
                ".sidebar #narrow-by-list": {
                    "accordion": {
                        "multipleCollapsible": true,
                        "active": [<?= $block->escapeHtml(implode(",", $block->getFiltersExpanded()))?>]
                    }
                }
            }
</script>
