<?php
/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>

<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed" data-amtheme-js="product-info-detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items"
             data-mage-init='{
                "tabs":{
                    "openedState":"active",
                    "icons": {
                       "header": "amtheme-icon",
                       "activeHeader": "amtheme-icon"
                    }
                },
                "amProductTabCaret":{}
             }'>
            <?php foreach ($detailedInfoGroup as $name): ?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     id="tab-label-<?= $block->escapeHtml($alias) ?>"
                     data-role="collapsible"
                     data-amtheme-js="item-title">
                    <a class="data switch"
                       id="tab-label-<?= $block->escapeHtml($alias) ?>-title"
                       tabindex="-1"
                       aria-label="label-<?= $block->escapeHtml($alias) ?>-title"
                       data-amtheme-js="<?= $block->escapeHtml($alias) ?>-tab-trigger"
                       data-toggle="trigger"
                       href="#<?= $block->escapeUrl($alias) ?>">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                     id="<?= $block->escapeHtml($alias) ?>"
                     data-amtheme-js="<?= $block->escapeHtml($alias) ?>"
                     aria-labelledby="tab-label-<?= $block->escapeHtml($alias) ?>-title"
                     data-role="content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
