<?php
/** @var \Magento\Review\Block\Form $block */

$reviewFormTrigger = 'review-form-open';
?>

<div class="review-add amtheme-popup-block amtheme-reviewform-block"
     tabindex="0"
     data-mage-init='{"amPopup":{"trigger": "<?= $block->escapeHtml($reviewFormTrigger); ?>"}}'>
    <div class="popup-inner">
        <button class="amtheme-button-close"
                tabindex="0"
                title="<?= $block->escapeHtmlAttr(__('Close')); ?>"
                aria-label="<?= $block->escapeHtmlAttr(__('Close')); ?>"
                data-amtheme-js="popup-close">
            <svg class="amtheme-icon -icon-close">
                <use xlink:href="#icon-close" />
            </svg>
        </button>
        <div class="form-heading">
            <h4 class="form-title">
                <?= $block->escapeHtml(__('Write your review')) ?>
            </h4>
            <span class="product-name">
                <?= $block->escapeHtml(__('About the ') . $block->getProductInfo()->getName()); ?>
            </span>
        </div>
        <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form action="<?= $block->escapeUrl($block->getAction()) ?>"
                  class="review-form"
                  method="post"
                  id="review-form"
                  data-role="product-review-form"
                  data-bind="scope: 'review-form'">
                <?= $block->getBlockHtml('formkey') ?>
                <?= $block->getChildHtml('form_fields_before') ?>
                <fieldset class="fieldset review-fieldset"
                          data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>"
                >
                    <legend class="legend review-legend">
                        <?= $block->escapeHtml(__("You're reviewing:")) ?>
                        <?= $block->escapeHtml($block->getProductInfo()->getName()) ?>
                    </legend>
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <span id="input-message-box"></span>
                        <fieldset class="field required review-field-ratings">
                            <legend class="label">
                                <?= $block->escapeHtml(__('Your Rating')) ?>
                            </legend>
                            <div class="nested product-review-table" id="product-review-table">
                                <?php foreach ($block->getRatings() as $_rating): ?>
                                    <div class="choice review-field-rating">
                                        <label class="label"
                                               id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label">
                                            <?= $block->escapeHtml($_rating->getRatingCode()) ?>
                                        </label>
                                        <div class="rating-stars-block">
                                            <?php $options = $_rating->getOptions();?>
                                            <?php $iterator = count($options); foreach (array_reverse($options) as $_option): ?>
                                                <input
                                                        type="radio"
                                                        name="ratings[<?= $block->escapeHtml($_rating->getId()) ?>]"
                                                        id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= $block->escapeHtml($_option->getValue()) ?>"
                                                        value="<?= $block->escapeHtml($_option->getId()) ?>"
                                                        class="radio"
                                                        data-validate="{'rating-required':true}"
                                                        aria-labelledby="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label
                                        <?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= $block->escapeHtml($_option->getValue()) ?>_label"
                                                />
                                                <label
                                                        class="rating-star rating-<?= $block->escapeHtml($iterator) ?>"
                                                        for="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= $block->escapeHtml($_option->getValue()) ?>"
                                                        title="<?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                                        id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= $block->escapeHtml($_option->getValue()) ?>_label">
                                                </label>
                                                <?php $iterator--; ?>
                                            <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </fieldset>
                    <?php endif ?>
                    <div class="field review-field-nickname required">
                        <label for="nickname_field" class="label">
                            <?= $block->escapeHtml(__('Nickname')) ?>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="nickname"
                                   id="nickname_field"
                                   class="input-text"
                                   data-validate="{required:true}"
                                   data-bind="value: nickname()"
                            />
                        </div>
                    </div>
                    <div class="field review-field-summary required">
                        <label for="summary_field" class="label">
                            <?= $block->escapeHtml(__('Summary')) ?>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="title"
                                   id="summary_field"
                                   class="input-text"
                                   data-validate="{required:true}"
                                   data-bind="value: review().title"
                            />
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label">
                            <?= $block->escapeHtml(__('Review')) ?>
                        </label>
                        <div class="control">
                            <textarea name="detail"
                                      id="review_field"
                                      cols="5"
                                      rows="3"
                                      data-validate="{required:true}"
                                      data-bind="value: review().detail"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="review-form-actions">
                    <button type="submit"
                            class="action submit"
                            title="<?= $block->escapeHtml(__('Send Review')) ?>"
                            aria-label="<?= $block->escapeHtml(__('Send Review')) ?>"
                    >
                        <?= $block->escapeHtml(__('Send Review')) ?>
                    </button>
                </div>
            </form>
            <script type="text/x-magento-init">
                {
                    "[data-role=product-review-form]": {
                        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                    },
                    "#review-form": {
                        "Magento_Review/js/error-placement": {},
                        "Magento_Review/js/validate-review": {}
                    }
                }
            </script>
        <?php else: ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
                </div>
            </div>
        <?php endif ?>
        </div>
    </div>
</div>
