<?php
/**
 * @var $block Magento\Theme\Block\Html\Footer
 * @var $viewModel Amasty\JetTheme\ViewModel\Footer\FooterViewModel
 * @var $escaper Magento\Framework\Escaper
 */

$viewModel = $block->getViewModel();
$isCustomMiniFooterEnabled = $viewModel->isCustomMiniFooterEnabled();
?>

<?php if ($isCustomMiniFooterEnabled): ?>
    <div class="amtheme-minifooter-block">
        <?= /* @noEscape */ $viewModel->getCustomMiniFooterContent(); ?>
    </div>
<?php else: ?>
    <small class="copyright">
        <span><?= $escaper->escapeHtml($block->getCopyright()) ?></span>
    </small>
<?php endif; ?>
