<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 * @var $paymentViewModel Amasty\JetTheme\ViewModel\PaymentViewModel
 * @var $escaper Magento\Framework\Escaper
 */

$viewModel = $block->getPaymentViewModel();
?>
<div class="amtheme-payment-methods">
    <ul class="amtheme-payments-list">
        <?php foreach ($viewModel->getPaymentLinks() as $paymentMethod): ?>
            <li class="amtheme-item">
                <?php if (!$paymentMethod->getDefaultIcon()): ?>
                    <img src="<?= $escaper->escapeHtmlAttr($viewModel->getPaymentImage($paymentMethod->getIcon())); ?>"
                         alt="<?= $escaper->escapeHtmlAttr($paymentMethod->getTitle()); ?>">
                <?php else: ?>
                    <?= /* @noEscape */ $paymentMethod->getDefaultIconContent()?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
