<?php
/** @var Magento\Customer\Block\Form\Edit $block */

$dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class);
$taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class);
$gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class);
$name = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class);
$minPassLength = $block->getMinimumPasswordLength();
$minChars = $block->getRequiredCharacterClassesNumber()
?>

<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">

    <?= $block->getChildHtml('form_additional_info') ?>

    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend">
            <?= $block->escapeHtml(__('Account Information')) ?>
        </legend>
        <div class="fields -double">
            <?= /* @noEscape */ $name->setObject($block->getCustomer())->toHtml() ?>
        </div>
    </fieldset>
    <?php if ($dob->isEnabled() || $taxvat->isEnabled() || $gender->isEnabled()): ?>
        <fieldset class="fieldset">
            <div class="fields -double">
                <?php if ($dob->isEnabled()): ?>
                    <?= /* @noEscape */ $dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
                <?php endif ?>
                <?php if ($taxvat->isEnabled()): ?>
                    <?= /* @noEscape */ $taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
                <?php endif ?>
                <?php if ($gender->isEnabled()): ?>
                    <?= /* @noEscape */ $gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
                <?php endif ?>
            </div>
        </fieldset>
    <?php endif ?>
    <?= $block->getChildHtml('fieldset_edit_info_additional') ?>
    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend">
            <span data-title="change-email-password">
                <?= $block->escapeHtml(__('Change Email and Password')) ?>
            </span>
        </legend>
        <div class="fields -double">
            <div class="field email required" data-container="change-email">
                <label class="label" for="email">
                    <?= $block->escapeHtml(__('New Email')) ?>
                </label>
                <div class="control">
                    <input type="email"
                           name="email"
                           id="email"
                           autocomplete="email"
                           data-input="change-email"
                           value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text" data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
            <div class="field password current required">
                <label class="label" for="current-password">
                    <?= $block->escapeHtml(__('Password')) ?>
                </label>
                <div class="control">
                    <input type="password"
                           class="input-text"
                           name="current_password"
                           id="current-password"
                           data-input="current-password"
                           autocomplete="off"
                    />
                </div>
            </div>
            <div class="field new password required" data-container="new-password">
                <label class="label" for="password">
                    <?= $block->escapeHtml(__('New Password')) ?>
                </label>
                <div class="control">
                    <input type="password"
                           class="input-text"
                           name="password"
                           id="password"
                           data-password-min-length="<?= $block->escapeHtmlAttr($minPassLength) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($minChars) ?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off"
                    />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirm password required" data-container="confirm-password">
                <label class="label" for="password-confirmation">
                    <?= $block->escapeHtml(__('Confirm')) ?>
                </label>
                <div class="control">
                    <input type="password"
                           class="input-text"
                           name="password_confirmation"
                           id="password-confirmation"
                           data-input="confirm-password"
                           autocomplete="off"
                    />
                </div>
            </div>
        </div>
    </fieldset>
    <div class="amtheme-account-actions">
        <div class="amtheme-fields">
            <div class="field choice -as-link">
                <input type="checkbox"
                       name="change_email"
                       id="change-email"
                       data-role="change-email"
                       value="1"
                       title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>"
                       class="checkbox"
                />
                <label class="label"
                       for="change-email">
                    <?= $block->escapeHtml(__('Change Email')) ?>
                </label>
            </div>
            <div class="field choice -as-link">
                <input type="checkbox"
                       name="change_password"
                       id="change-password"
                       data-role="change-password"
                       value="1"
                       title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"
                    <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"
                />
                <label class="label"
                       for="change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </label>
            </div>
        </div>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit"
                        class="action save primary"
                        aria-label="<?= $block->escapeHtml(__('Save')) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                    <?= $block->escapeHtml(__('Save')) ?>
                </button>
            </div>
            <div class="secondary">
                <a class="action back"
                   aria-label="<?= $block->escapeHtml(__('Go back')) ?>"
                   title="<?= $block->escapeHtml(__('Go back')) ?>"
                   href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                    <?= $block->escapeHtml(__('Go back')) ?>
                </a>
            </div>
        </div>
    </div>
</form>

<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){
        var dataForm = $('#form-validate'),
            ignore = <?= /* @noEscape */ $dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
        <?php if ($dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');

                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs(__('Change Email')) ?>",
                "titleChangePassword": "<?= $block->escapeJs(__('Change Password')) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs(__('Change Email and Password')) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
