<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 * @var \Magento\Framework\Escaper $escaper
 */

$item = $block->getData('item');
$isIconsAvailable = $block->getData('isIconsAvailable');
?>

<a if="item.isVisible"
   class="ammenu-link"
   data-bind="
        event: {
            mouseenter: function () {
                item.isActive(true);
                item.isHover(true);
            },
            mouseleave: function () {
                item.isHover(false);
                item.isActive(false);
            }
        },
        style: {
            color: item.color() ? item.color() : ''
        },
        attr: { href: item.url ? item.url : '#' },
        css: { '-current': item.current }">
   <?php if ($isIconsAvailable && isset($item['icon'])): ?>
       <?= $block->getChildBlock('ammenu.top.menu.icon')->setData('item', $item)->toHtml() ?>
   <?php endif; ?>

    <p class="ammenu-text-block">
           <span class="ammenu-text"><?= $escaper->escapeHtml($item['name']) ?></span>
        <?php if (isset($item['label'])): ?>
            <span class="ammenu-label"
                  style="
                      background: <?= $escaper->escapeHtmlAttr($item['label']['label_background_color'] ?? '') ?>;
                      color: <?= $escaper->escapeHtmlAttr($item['label']['label_text_color'] ?? '') ?>;">
                <?= $escaper->escapeHtml($item['label']['label'] ?? '') ?>
            </span>
        <?php endif; ?>
   </p>
</a>
