<?php
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */
?>

<?php if ($block->getCurrencyCount() > 1): ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtml($id) ?>">
        <strong class="label switcher-label"><?= $block->escapeHtml(__('Currency')) ?></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-currency-trigger<?= $block->escapeHtml($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <svg class="amtheme-icon" focusable="false">
                    <use xlink:href="#icon-currency"/>
                </svg>
                <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                    <?= $block->escapeHtml($currentCurrencyCode) ?>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($currencies as $_code => $_name): ?>
                    <?php if ($_code != $currentCurrencyCode): ?>
                        <li class="currency-<?= $block->escapeHtml($_code) ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?> - <?= $block->escapeHtml($_name) ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
