<?php
/**
 * @var $block Magento\Catalog\Block\Product\View
 * @var $escaper Magento\Framework\Escaper
 */

/** @var $viewModel \Nri\LowStock\ViewModel\LowStock\LowStock */
$viewModel = $block->getViewModel();
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()):?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($viewModel->getLowStockMessageMessage()) :?>
                <p class="low-stock-message"><?= $viewModel->getLowStockMessageMessage() ?></p>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml($buttonTitle) ?>"
                        class="action primary tocart"
                        data-amtheme-js="addtocart-button"
                        id="product-addtocart-button">
                    <span class="amtheme-title">
                        <?= $escaper->escapeHtml($buttonTitle) ?>
                    </span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
