<?php
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
// phpcs:disable Magento2.PHP.ShortEchoSyntax.ShortEchoTag

/** @var $block \Magento\Ui\Block\Wrapper */
?>

<?php /* @noEscape */ echo $block->renderApp([
    'widget_columns' => [
        'additionalClasses' => 'am-widget block-compared-products-grid',
        'displayMode' => 'grid'
    ],
    'image' => [
        'imageCode' => 'recently_compared_products_grid_content_widget'
    ]
]);
