<?php
/**
 * @var $block Magento\Swatches\Block\Product\Renderer\Configurable
 * @var $configurableViewModel Magento\Swatches\ViewModel\Product\Renderer\Configurable
 * @var $productViewModel Amasty\JetTheme\ViewModel\ProductPage\ProductPageViewModel
 * @var $escaper Magento\Framework\Escaper
 */

$configurableViewModel = $block->getConfigurableViewModel();
$productViewModel = $block->getProductViewModel();
$swatchType = $productViewModel ? $productViewModel->getSwatchesType() : false;
?>
<div class="swatch-opt <?= $swatchType ? '-' . $escaper->escapeHtmlAttr($swatchType) : ''?>" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getMediaCallback())) ?>",
                "gallerySwitchStrategy": "<?= $escaper->escapeJs($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct')) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $escaper->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>
