<?php
/** @var \Magento\Multishipping\Block\Checkout\Address\Select $block */
?>

<div class="multicheckout">
    <div class="block block-billing">
    <?php foreach ($block->getAddress() as $address): ?>
        <div class="box box-billing-address">
            <div class="box-content">
                <address>
                    <?= $block->getAddressAsHtml($address) ?>
                </address>
                <?php if ($block->isAddressDefaultBilling($address) || $block->isAddressDefaultShipping($address)): ?>
                    <div class="amtheme-default-mark">
                    <?php if ($block->isAddressDefaultBilling($address)): ?>
                        <span class="amtheme-mark"><?= $block->escapeHtml(__('Default Billing')); ?></span>
                    <?php endif; ?>
                    <?php if ($block->isAddressDefaultShipping($address)): ?>
                        <span class="amtheme-mark"><?= $block->escapeHtml(__('Default Shipping')); ?></span>
                    <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="box-actions">
                <a href="<?= $block->escapeUrl($block->getSetAddressUrl($address)); ?>"
                   class="action select"
                   title="<?= $block->escapeHtml(__('Select Address')); ?>">
                    <?= $block->escapeHtml(__('Select Address')); ?>
                </a>
                <a href="<?= $block->escapeUrl($block->getEditAddressUrl($address)); ?>"
                   class="action edit"
                   title="<?= $block->escapeHtml(__('Edit Address')); ?>">
                    <?= $block->escapeHtml(__('Edit')); ?>
                </a>
            </div>
        </div>
    <?php endforeach; ?>
        <div class="actions-toolbar">
            <button type="button"
                    class="action add outline"
                    role="add-address"
                    title="<?= $block->escapeHtmlAttr(__('Add New Address')); ?>">
                <?= $block->escapeHtml(__('Add New Address')); ?>
            </button>
        </div>
    </div>
    <div class="actions-toolbar">
        <a href="<?= $block->escapeUrl($block->getBackUrl()); ?>"
           class="action back"
           title="<?= $block->escapeHtml(__('Back to Billing Information')); ?>">
            <svg class="amtheme-icon">
                <use xlink:href="#icon-arrow-left-min"></use>
            </svg>
            <?= $block->escapeHtml(__('Back to Billing Information')); ?>
        </a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".action": {
            "address": {
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeUrl($block->getAddNewUrl()); ?>"
            }
        }
    }
</script>
