<?php
/**
 * @var Amasty\ThankYouPage\Block\Onepage\Success\Types\Crosssell $block
 * @var Magento\Framework\Escaper $escaper
 */

$isMarkup = $block->isMarkupEnabled();
$width = $block->getWidth();
$itemsHtml = $block->getItemsHtml();
?>

<?php if ($isMarkup): ?>
    <div class="amtyblock amtyblock-cross-sell" style="width: <?= $escaper->escapeHtmlAttr($width); ?>%">
<?php endif;?>

<?= /* @noEscape */ $itemsHtml; ?>

<?php if ($isMarkup): ?>
    </div>
<?php endif; ?>
