<?php
/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtml($id) ?>">
        <strong class="label switcher-label"><?= $block->escapeHtml(__('Language')) ?></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtml($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <svg class="amtheme-icon" focusable="false">
                    <use xlink:href="#icon-language"/>
                </svg>
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <?= $block->escapeHtml($block->getStoreName()) ?>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="#"
                               data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'
                               title="<?= $block->escapeHtml($_lang->getName()) ?>">
                               <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                       </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
