<?php
/** @var $block \Magento\Shipping\Block\Tracking\Link */

$order = $block->getOrder();
?>

<a href="#" class="action track outline" title="<?= $block->escapeHtmlAttr($block->getLabel()) ?>"
   data-mage-init='{"popupWindow": {
        "windowURL":"<?= $block->escapeUrl($block->getWindowUrl($order)) ?>",
        "windowName":"trackorder",
        "width":800,
        "height":600,
        "left":0,
        "top":0,
        "resizable":1,
        "scrollbars":1
    }}'>
    <?= $block->escapeHtml($block->getLabel()) ?>
</a>
