<?php
/** @var $block \Amasty\ShopbyLite\Block\Navigation\SwatchRenderer */
/** @var \Magento\Framework\Escaper $escaper */
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration.BreakIndent

use Magento\Swatches\Model\Swatch;

$filterCode = $block->getFilter()->getRequestVar();
?>
<?php $swatchData = $block->getSwatchData(); ?>
<form data-am-js="am-ranges"
      data-amshopby-filter="<?= $escaper->escapeHtmlAttr($filterCode) ?>"
      data-amshopby-filter-request-var="<?= $escaper->escapeHtmlAttr($block->getFilter()->getRequestVar()) ?>"
      autocomplete="off">
    <div class="swatch-attribute swatch-layered <?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
         attribute-code="<?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
         data-attribute-code="<?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
         attribute-id="<?= $escaper->escapeHtmlAttr($swatchData['attribute_id']) ?>"
         data-attribute-id="<?= $escaper->escapeHtmlAttr($swatchData['attribute_id']) ?>">
        <div class="swatch-attribute-options clearfix">
            <?php foreach ($swatchData['options'] as $option => $label): ?>
                <a href="<?= $escaper->escapeUrl($label['link']) ?>"
                   aria-label="<?= $escaper->escapeHtmlAttr($label['label']) ?>"
                   class="swatch-option-link-layered am-swatch-link"
                   data-am-js="filter-item-default">
                    <?php if (isset($swatchData['swatches'][$option]['type'])): ?>
                        <?php switch ($swatchData['swatches'][$option]['type']):
                                case Swatch::SWATCH_TYPE_EMPTY:
                                    $class = '';
                                    $optionType = 3;
                                    $swatchThumbPath = '';
                                    $swatchTooltipValue = '';
                                    $style = '';
                                    $value = '';
                                break;
                                case Swatch::SWATCH_TYPE_VISUAL_IMAGE:
                                    $class = 'image';
                                    $optionType = 2;
                                    $swatchTooltipValue = '';
                                    $swatchThumbPath = $block->getSwatchPath(
                                        'swatch_thumb',
                                        $swatchData['swatches'][$option]['value']
                                    );
                                    $swatchImagePath = $block->getSwatchPath(
                                        'swatch_image',
                                        $swatchData['swatches'][$option]['value']
                                    );
                                    $style = "background: url(" . $swatchImagePath . ") no-repeat center; background-size: initial;";
                                    $value = '';
                                break;
                                case Swatch::SWATCH_TYPE_VISUAL_COLOR:
                                    $class = 'color';
                                    $optionType = 1;
                                    $swatchThumbPath = '';
                                    $swatchTooltipValue = $swatchData['swatches'][$option]['value'];
                                    $style = "background: " . $swatchData['swatches'][$option]['value'] . " no-repeat center; background-size: initial;";
                                    $value = '';
                                break;
                                case Swatch::SWATCH_TYPE_TEXTUAL:
                                default:
                                    $class = 'text';
                                    $optionType = 0;
                                    $swatchThumbPath = '';
                                    $swatchTooltipValue = '';
                                    $style = '';
                                    $value = $swatchData['swatches'][$option]['value'];
                                break;
                            endswitch; ?>

                        <div class="swatch-option
                            <?= /* @noEscape */ $label['custom_style'] ?> <?= /* @noEscape */ $class; ?> "
                             data-am-js="swatch-item"
                             option-type="<?= /* @noEscape */ $optionType; ?>"
                             option-id="<?= /* @noEscape */ $option ?>"
                             option-label="<?= $block->escapeHtml($label['label']) ?>"
                             option-tooltip-thumb="<?= /* @noEscape */ $swatchThumbPath ?>"
                             option-tooltip-value="<?= /* @noEscape */ $swatchTooltipValue ?>"
                             data-option-type="<?= /* @noEscape */ $optionType; ?>"
                             data-option-id="<?= /* @noEscape */ $option ?>"
                             data-option-label="<?= $block->escapeHtml($label['label']) ?>"
                             data-option-tooltip-thumb="<?= /* @noEscape */ $swatchThumbPath ?>"
                             data-option-tooltip-value="<?= /* @noEscape */ $swatchTooltipValue ?>"
                             style="<?= /* @noEscape */ $style ?>">
                            <?= /* @noEscape */ $value ?>
                        </div>
                    <?php endif; ?>

                    <input  class="input -hidden"
                            name="amshopby[<?= /* @noEscape */ $block->getFilter()->getRequestVar(); ?>][]"
                            value="<?= /* @noEscape */ $option; ?>"
                            type="<?= /* @noEscape */ $block->getFilter()->isMultiSelectAllowed() ? 'checkbox' : 'radio' ?>"
                            <?= /* @noEscape */ $label['selected'] ? 'checked' : ''; ?>
                    />
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</form>

<script>
    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('[data-am-js="swatch-item"]').SwatchRendererTooltip();
    });
</script>
