<?php
/**
 * @var \Magento\Paypal\Block\Billing\Agreement\View $block
 */

$relatedOrders = $block->getRelatedOrders();
?>
<div class="block block-billing-agreements-view">
    <?php if ($block->getCanCancel()): ?>
        <div class="amtheme-info">
            <button class="amtheme-cancel-agreement button-as-link cancel"
                data-mage-init='{"Magento_Paypal/js/in-context/billing-agreement": {
                    "cancelMessage" : "<?= $block->escapeHtml(__('Are you sure you want to do this?')) ?>",
                    "cancelUrl" : "<?= $block->escapeUrl($block->getCancelUrl()) ?>"
                }}'
                type="button"
                title="<?= $block->escapeHtmlAttr(__('Cancel')) ?>" />
                <?= $block->escapeHtml(__('Cancel')) ?>
                <svg class="amtheme-icon">
                    <use xlink:href="#icon-arrow-right-min" />
                </svg>
            </button>
        </div>
    <?php endif; ?>
    <div class="block-title">
        <?= $block->escapeHtml(__('Agreement Information')) ?>
    </div>
    <div class="block-content">
        <div class="table-wrapper billing-agreements-view">
            <table class="data table table-billing-agreements-view">
                <caption class="table-caption"><?= $block->escapeHtml(__('Agreement Information')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Reference ID:')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status:')) ?></th>
                        <th scope="col" class="col created"><?= $block->escapeHtml(__('Created:')) ?></th>
                        <?php if ($block->getAgreementUpdatedAt()): ?>
                            <th scope="col" class="col updated"><?= $block->escapeHtml(__('Updated:')) ?></th>
                        <?php endif; ?>
                        <th scope="col" class="col payment"><?= $block->escapeHtml(__('Payment Method:')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Reference ID:')) ?>" class="col id">
                            <?= $block->escapeHtml($block->getReferenceId()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Status:')) ?>" class="col status">
                            <?= $block->escapeHtml($block->getAgreementStatus()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Created:')) ?>" class="col created">
                            <?= $block->escapeHtml($block->getAgreementCreatedAt()) ?>
                        </td>
                        <?php if ($block->getAgreementUpdatedAt()): ?>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Updated:')) ?>" class="col updated">
                                <?= $block->escapeHtml($block->getAgreementUpdatedAt()) ?>
                            </td>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Payment Method:')) ?>" class="col payment">
                            <?= $block->escapeHtml($block->getPaymentMethodTitle()) ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php if (count($relatedOrders) > 0): ?>
    <div class="block block-billing-orders-view">
        <?= $block->getChildHtml('pager') ?>
        <div class="block-title">
            <?= $block->escapeHtml(__('Related Orders')) ?>
        </div>
        <div class="block-content">
            <div class="table-wrapper billing-agreements-related">
                <table class="data table table-billing-agreements-related" id="related-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Related Orders')) ?></caption>
                    <thead>
                        <tr>
                            <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                            <th scope="col" class="col shipto"><?= $block->escapeHtml(__('Ship To')) ?></th>
                            <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                            <th scope="col" class="col status"><?= $block->escapeHtml(__('Order Status')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($relatedOrders as $order): ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="col id">
                                    <a href="<?= $block->escapeUrl($block
                                        ->getOrderItemValue($order, 'view_url')) ?>"
                                       class="action view"
                                       title="<?= $block->escapeHtmlAttr(__('View Order')) ?>">
                                        <?= $block->escapeHtml($block
                                            ->getOrderItemValue($order, 'order_increment_id')) ?>
                                    </a>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date">
                                    <?= $block->escapeHtml($block->getOrderItemValue($order, 'created_at')) ?>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="col shipto">
                                    <?= $block->escapeHtml($block->getOrderItemValue($order, 'shipping_address')) ?>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="col total">
                                    <?= /* @noEscape */ $block->getOrderItemValue($order, 'order_total') ?>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Order Status')) ?>" class="col status">
                                    <span class="amtheme-status -<?= $block->escapeHtml($order->getState()) ?>">
                                        <?= $block->escapeHtml($order->getStatusLabel()) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>
