<?php
/**
 * @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block
 * @var Magento\Framework\Escaper $escaper
 */

$amViewModel = $block->getData('amAjaxViewModel');
$isAjaxWishListEnabled = $amViewModel ? $amViewModel->isEnabledAjaxAddToWishlist() : false;
$dataPost = $block->getAddToWishlistParams($block->getParentBlock()->getProduct());
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <div class="towishlist-wrap">
        <a href="#"
           class="action towishlist amtheme-circle-icon"
           title="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
           aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
           data-post='<?= /* @noEscape */ $dataPost ?>'
           <?php if ($isAjaxWishListEnabled): ?>
                data-amtheme-js="ajax-wishlist"
           <?php else: ?>
                data-action="add-to-wishlist"
           <?php endif; ?>
           role="button">
            <svg class="amtheme-icon -hover-bg" focusable="false">
                <use xlink:href="#icon-wishlist" />
            </svg>
        </a>
    </div>
<?php endif; ?>

<?php if ($isAjaxWishListEnabled):?>
    <script type="text/x-magento-init">
            {
                "[data-amtheme-js=ajax-wishlist]": {
                    "amAjaxWishlist": {
                        "actionUrl": "<?= /* @noEscape */ $amViewModel->getAjaxAddToWishlist(); ?>"
                    }
                }
            }
        </script>
<?php endif; ?>
