<?php
/** @var $block \Magento\Sales\Block\Order\Info */

$order = $block->getOrder();
?>

<div class="block block-order-details-view">
    <div class="block-title">
        <?= $block->escapeHtml(__('Order Information')) ?>
    </div>
    <div class="block-content">
        <?php if (!$order->getIsVirtual()): ?>
            <div class="box column -address box-order-shipping-address">
                <strong class="box-title"><?= $block->escapeHtml(__('Shipping Address')) ?></strong>
                <address class="box-content">
                    <?= /* @noEscape */ $block->getFormattedAddress($order->getShippingAddress()) ?>
                </address>
            </div>
        <?php endif; ?>

        <div class="box column -address box-order-billing-address">
            <strong class="box-title">
                <?= $block->escapeHtml(__('Billing Address')) ?>
            </strong>
            <address class="box-content">
                <?= /* @noEscape */ $block->getFormattedAddress($order->getBillingAddress()) ?>
            </address>
        </div>

        <div class="column -methods">
            <?php if (!$order->getIsVirtual()): ?>
                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <?= $block->escapeHtml(__('Shipping Method')) ?>
                    </strong>
                    <div class="box-content">
                        <?php if ($order->getShippingDescription()): ?>
                            <?= $block->escapeHtml($order->getShippingDescription()) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('No shipping information available')) ?>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="box box-order-billing-method<?= $order->getIsVirtual() ? ' -fullwidth' : ''?>">
                <strong class="box-title">
                    <?= $block->escapeHtml(__('Payment Method')) ?>
                </strong>
                <div class="box-content">
                    <?= $block->getPaymentInfoHtml() ?>
                </div>
            </div>
        </div>
    </div>
</div>
