<?php
/** @var $block \Magento\Sales\Block\Order\Recent */

$orders = $block->getOrders();
$count = count($orders);
// phpcs:ignore
$reorderHelper = $this->helper(\Magento\Sales\Helper\Reorder::class);
// phpcs:ignore
$postHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
?>
<div class="amtheme-card-block amtheme-dashboard-orders -with-table">
    <div class="amtheme-heading">
        <span class="amtheme-title order">
            <?= $block->escapeHtml(__('Recent Orders')) ?>
        </span>
        <?php if ($count > 0): ?>
            <a class="action view"
               title="<?= $block->escapeHtml(__('View All')) ?>"
               href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                <?= $block->escapeHtml(__('View All')) ?>
            </a>
        <?php endif; ?>
    </div>

    <div class="amtheme-content">
    <?= $block->getChildHtml() ?>
    <?php if ($count > 0): ?>
        <div class="table-wrapper orders-recent">
            <table class="data table table-order-items recent" id="my-orders-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Recent Orders')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                        <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($orders as $order):
                        $canReorder = $reorderHelper->canReorder($order->getEntityId());
                        $shipTo = $order->getShippingAddress()
                            ? $block->escapeHtml($order->getShippingAddress()->getName())
                            : '&nbsp;'; ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="col id">
                                <a href="<?= $block->escapeUrl($block->getViewUrl($order)) ?>"
                                   title="<?= $block->escapeHtmlAttr(__('View Order')) ?>"
                                   aria-label="<?= $block->escapeHtmlAttr(__('Order Id')) ?>">
                                    <?= $block->escapeHtml($order->getRealOrderId()) ?>
                                </a>
                            </td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date">
                                <?= $block->escapeHtml($block->formatDate($order->getCreatedAt())) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="col shipping">
                                <?= /* @noEscape */ $shipTo ?>
                            </td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="col total">
                                <?= /* @noEscape */ $order->formatPrice($order->getGrandTotal()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>"
                                class="col status">
                                <span class="amtheme-status -<?= $block->escapeHtml($order->getState()) ?>">
                                    <?= $block->escapeHtml($order->getStatusLabel()) ?>
                                </span>
                            </td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                                <?php if ($canReorder):
                                    $reorderUrl = $postHelper->getPostData($block->getReorderUrl($order)); ?>
                                    <a href="#"
                                       data-post='<?= /* @noEscape */ $reorderUrl ?>'
                                       class="action order"
                                       title="<?= $block->escapeHtmlAttr(__('Reorder')) ?>"
                                       aria-label="<?= $block->escapeHtmlAttr(__('Reorder')) ?>">
                                        <?= $block->escapeHtml(__('Reorder')) ?>
                                    </a>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
        </div>
    <?php endif; ?>
    </div>
</div>
