<?php
/**
 * @var $block Magento\Catalog\Block\Product\AbstractProduct
 * @var $amProductCaretViewModel Amasty\JetTheme\ViewModel\ProductCaret\ProductCaretConfigurationViewModel
 * @var $escaper Magento\Framework\Escaper
 */

$amProductCaretViewModel = $block->getAmProductCaretViewModel();
$isProductCaretEnabled = $amProductCaretViewModel ? $amProductCaretViewModel->isProductCaretEnabled() : null;
$isProductSliderEnabled = true;

switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = __('A few recommendations');
            $items = $block->getItems();
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;
            $class = 'widget' . ' ' . $type;
            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist): ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
                 data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                 data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
                 data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
                 data-mage-init='{"upsellProducts":{}}'
                 data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
                 data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= $escaper->escapeHtmlAttr($class) ?>">
    <?php endif; ?>
            <div class="block-title title"
                 id="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading"
                 role="heading"
                 title="<?= $escaper->escapeHtmlAttr($title) ?>"
                 aria-level="2">
                <?= $escaper->escapeHtml($title) ?>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $escaper->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items amtheme-products-secondary <?= $isProductSliderEnabled ? ' amtheme-slick-slider' : '' ?>"
                        <?php if ($isProductSliderEnabled): ?>
                            data-mage-init='{"slickSlider": {
                                "isOnMobile": false,
                                "sliderOptions": {
                                <?php if ($isProductCaretEnabled && $isProductCaretEnabled === 'sidebar'): ?>
                                    "slidesToShow": 3,
                                <?php else: ?>
                                    "slidesToShow": 5,
                                    "responsive": [
                                        {
                                            "breakpoint": 1280,
                                            "settings": {
                                                "slidesToShow": 4
                                            }
                                        },
                                        {
                                            "breakpoint": 960,
                                            "settings": {
                                                "slidesToShow": 3
                                            }
                                        }
                                    ],
                                <?php endif; ?>
                                    "dots": true
                                }
                            }}'
                            <?php endif; ?>
                        >
                        <?php foreach ($items as $item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$item->isComposite() && $item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <li class="item product product-item" style="display: none;">
                            <?php else: ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                <a href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                                   title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <span class="product name product-item-name">
                                        <a class="product-item-link"
                                           title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                           href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>">
                                            <?= $escaper->escapeHtml($item->getName()) ?>
                                        </a>
                                    </span>

                                    <?= /* @noEscape */ $block->getProductPrice($item) ?>
                                    <?php if ($templateType):?>
                                        <?= $block->getReviewsSummaryHtml($item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showCart): ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($item->isSaleable()): ?>
                                                <?php if ($item->getTypeInstance()->hasRequiredOptions($item)): ?>
                                                    <button type="button"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary"
                                                            data-mage-init='{"redirectUrl":{"url":"<?= $escaper->escapeUrl($block->getAddToCartUrl($item)) ?>"}}'
                                                    >
                                                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                    </button>
                                                <?php else: ?>
                                                    <?php
                                                    // phpcs:ignore
                                                    $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($item), ['product' => $item->getEntityId()]);
                                                    ?>
                                                    <button type="button"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary"
                                                            data-post='<?= $escaper->escapeHtmlAttr(__($postData)) ?>'
                                                    >
                                                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <?= $escaper->escapeHtml(__('Out of stock')) ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
<?php endif;?>
