<?php
/**
 * @author    Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package   Amasty_ThankYouPage
 */

declare(strict_types=1);

namespace Amasty\ThankYouPage\Api;

interface ConfigCreateAccountInterface extends ConfigCustomInterface
{

    /**
     * @return bool
     */
    public function isPasswordAutoGenerated(): bool;

    /**
     * @return bool
     */
    public function isEmailFieldVisible(): bool;

    /**
     * @return bool
     */
    public function isTermsAndConditionsVisible(): bool;

    /**
     * @return string|null
     */
    public function getTermsText(): ?string;
}
