<section class="amtheme-maintenance-container">
    <div class="amtheme-plate -yellow"></div>
    <div class="amtheme-header">
        <img src="images/logo_maintenance-x1.png" alt="JetTheme Logo'">
    </div>
    <div class="amtheme-content">
        <picture class="amtheme-dice">
            <source srcset="images/dice-x1.jpg 1x, images/dice-x2.jpg 2x" media="(min-width: 1440px)">
            <img src="images/dice-x1.jpg" alt="Dice Image">
        </picture>
        <h1 class="amtheme-title">We've got something new <span class="amtheme-text -green">for you</span></h1>
        <p class="amtheme-description">We're down for a short time to perform maintenance on site to give you the best possible experience. Check back soon!</p>
    </div>
</section>
