<?php
/**
 * @var $block Magento\Catalog\Block\Product\View
 * @var $escaper Magento\Framework\Escaper
 */

$_product = $block->getProduct();
?>

<?php if ($_product->isSaleable()):?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Update Cart')) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Update Cart')) ?>"
                        data-amtheme-js="addtocart-button"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <?= $escaper->escapeHtml(__('Update Cart')) ?>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
